apiVersion: apps/v1
kind: Deployment
metadata:
  name: driverms
spec:
  replicas: 2
  selector:
    matchLabels:
      app: driverms
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: driverms
    spec:
      containers:
        - name:  driverms-app
          image: tharindub/driverms
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 100m