name: Build an deploy

on:
  push:
    branches:
      - main
env:
  DEPLOYMENT_NAME: driverms
  PROJECT_ID: ${{ secrets.GKA_PROJECT }}
  GKE_CLUSTER: cluster-1-tharindu
  GKE_ZONE: us-central1-c

jobs:
  setup-build-publish:
    name: Setup env, build application and publish
    runs-on: ubuntu-latest

    steps:
      -
        run: echo "Build Started"
      -
        name: Checkout repository
        uses: actions/checkout@v3
      -
        run: echo "Project repository has been clone in to the runner"

      #Create resources dir
      - name: Crete directory
        run: mkdir -p src/main/resources/
      #Create application property file
      -
        name: Create application property file
        uses: "finnp/create-file-action@master"
        env:
          FILE_NAME: "src/main/resources/application.properties"
          FILE_DATA: ${{ secrets.APPLICATION_PROPERTIES }}

      #Setup JDK
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "11"
          server-id: github
          settings-path: ${{ github.workspace}}
      #Build with maven
      - name: Build with maven
        run: mvn clean package -DskipTests

      #Login to docker  hub
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{env.DEPLOYMENT_NAME}}:${{ github.sha }}




  deploy:
    name: deploy application
    runs-on: ubuntu-latest

    steps:
      #setup google clod auth
      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"
      # Setup gcloud CLI
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      # Get the GKE credentials so we can deploy to the cluster
      - run: |-
          gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"
      #Deploy to K8s
      - name: Deploy
        run: |-
          kubectl apply -f k8s/deployment.yaml -f k8s/service.yaml
          kubectl set image deployment/$DEPLOYMENT_NAME driverms-app=tharindub/driverms:${{ github.sha }}
          kubectl rollout status deployment/$DEPLOYMENT_NAME
          kubectl get services -o wide
