name: Build an deploy

on:
  push:
    branches:
      - main

jobs:
  setup-build-publish:
    name: Setup env, build application and publish
    runs-on: ubuntu-latest

    steps:
      -
        run: echo "Build Started"
      -
        name: Checkout repository
        uses: actions/checkout@v3
      -
        run: echo "Project repository has been clone in to the runner"